### ISSUE TITLE
Store forces loading state rerender on every update

### ISSUE THREAD

**Issue by ncor** [AlekseyLu/todo-list-react#1]
# Problem
Task list components use methods provided by the global task store, such as update, edit, and delete. The bug is that the mutations force the store to update the loading state, which causes the component to display an extra loading stage.
https://t.me/react_js/2192693

# Solution
In the store mutation methods, immediately update the local state, and send the request itself at the end, without updating the loading state.

## Example solution
```ts
updateTodo: async (id: number, complete: boolean, ...) => {
    set((state) => ({
        tasks: state.tasks.map((task) => {
            if (task.id === response.id)
                return { task, complete };
        }),
    }));
    actualUpdateRequest();
    // ...
},
```

**Comment by AlekseyLu** [comment]
Исправил условие появления спинера, стало работать приятней
Плюсам поправил:
 - Регистрацию, добавил регулярку
- Отображение всех пользователей в списке запроса

**Comment by ncor** [comment]
> Исправил условие появления спинера, стало работать приятней
> Плюсам поправил:
>  - Регистрацию, добавил регулярку
> - Отображение всех пользователей в списке запроса

Отлично. Прикрепи сюда мердж реквест или коммит, так положено. Также закрой этот топик.

**Comment by AlekseyLu** [comment]
Исправлено
https://github.com/AlekseyLu/todo-list-react/commit/f418d33e03af7809555fd6ec78bf73ed2ccb87cc
